image: growerp/flutter-sdk-image:3.16.0

pipelines:
  default:
    - step: &lint
        name: Linting
        script:
          - flutter --version
          - flutter pub get
          - flutter analyze
    - step: &unit_tests
        name: Unit Tests
        script:
          - flutter --version
          - flutter pub get
          - flutter test --coverage --test-randomize-ordering-seed=random
    - step: &widget_tests
        name: Widget Tests
        script:
          - flutter --version
          - flutter pub get
          - flutter test --coverage --test-randomize-ordering-seed=random
    - step: &build_apk
        name: Build APK
        script:
          - sed -i 's/com.example.esteira_imc/com.YOURDOMAIN.esteira_imc/g' android/app/build.gradle
          - sed -i 's/versionCode 1/versionCode 10/g' android/app/build.gradle
          - sed -i 's/versionName "1.0.0"/versionName "1.0.1"/g' android/app/build.gradle
          - flutter --version
          - flutter pub get
          - flutter build apk --debug
        artifacts:
          - build/app/outputs/**/*.apk
    - step: &integration_tests
        name: Integration Tests
        script:
          - flutter --version
          - flutter pub get
          - flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart