name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Linting
        run: flutter analyze
      - name: Unit Tests
        run: flutter test --coverage --test-randomize-ordering-seed=random
      - name: Widget Tests
        run: flutter test --coverage --test-randomize-ordering-seed=random
      - name: Build APK
        run: |
          sed -i 's/com.example.esteira_imc/com.YOURDOMAIN.esteira_imc/g' android/app/build.gradle
          sed -i 's/versionCode 1/versionCode 10/g' android/app/build.gradle
          sed -i 's/versionName "1.0.0"/versionName "1.0.1"/g' android/app/build.gradle
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          system-image-api-level: 29 # Use a lower API level
          target: default # Use a minimal system image
          avd-name: test
          arch: x86_64
          profile: Nexus 5 # Use a smaller device profile
          force-avd-creation: false
          emulator-options: -no-window -no-audio -no-boot-anim -accel off -no-snapshot # Disable unnecessary features
          emulator-boot-timeout: 300 # Reduce the timeout to 5 minutes
          pre-emulator-launch-script: |
            echo "Waiting for emulator to boot..."
          script: |
            flutter pub get
            flutter build apk --debug
            flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart