name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Enable web support for Flutter
      - name: Enable Flutter Web Support
        run: flutter config --enable-web

      # Install dependencies required for Chromium browser
      - name: Install Dependencies for Headless Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libnss3 libxss1 libasound2 fonts-liberation libappindicator3-1 libgbm-dev || sudo apt-get install -y liboss4-salsa-asound2

      # Install Chromium browser
      - name: Install Chromium Browser
        run: sudo apt-get install -y chromium-browser

      # Install closest matching Chromedriver version
      - name: Install Closest Chromedriver Version
        run: |
          # Use the major version only (135)
          CHROMIUM_MAJOR_VERSION=$(echo "135.0.7049" | cut -d'.' -f1)
          echo "Using Chromedriver version $CHROMIUM_MAJOR_VERSION"
          wget https://chromedriver.storage.googleapis.com/$CHROMIUM_MAJOR_VERSION.0.0/chromedriver_linux64.zip || { echo "Chromedriver version $CHROMIUM_MAJOR_VERSION not found"; exit 1; }
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/
          rm chromedriver_linux64.zip
          chromedriver --version

      # Start Chromedriver
      - name: Start Chromedriver
        run: |
          nohup chromedriver --port=4444 --url-base=/wd/hub --whitelisted-ips &

      # Verify Chromedriver is running on port 4444
      - name: Verify Chromedriver on Port 4444
        run: |
          netstat -tuln | grep 4444 || { echo "Chromedriver not running on port 4444"; exit 1; }

      # Run integration tests using the web-server device
      - name: Run Integration Tests with Web-Server
        env:
          CHROME_EXECUTABLE: /snap/bin/chromium --headless --disable-gpu --no-sandbox
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server