name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Enable web support for Flutter
      - name: Enable Flutter Web Support
        run: flutter config --enable-web

      # Install Pre-built Chromium and Chromedriver based on Build Number
      - name: Install Pre-built Chromium and Chromedriver
        run: |
          # Define Chromium version
          CHROMIUM_VERSION="114.0.5735.90"

          # Get Chromium build number corresponding to the version
          BUILD_NUMBER=$(curl -s https://omahaproxy.appspot.com/deps.json?version=$CHROMIUM_VERSION | jq -r '.chromium_base_position')
          if [ -z "$BUILD_NUMBER" ]; then
            echo "Failed to find build number for Chromium version $CHROMIUM_VERSION"
            exit 1
          fi
          echo "Detected build number: $BUILD_NUMBER"

          # Download Chromium
          wget https://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/$BUILD_NUMBER/chrome-linux.zip
          unzip chrome-linux.zip
          sudo mv chrome-linux /usr/local/chromium

          # Download Chromedriver
          wget https://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/$BUILD_NUMBER/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/

          # Verify Installation
          /usr/local/chromium/chrome --version
          chromedriver --version

      # Start Chromedriver
      - name: Start Chromedriver
        run: |
          nohup chromedriver --port=4444 --url-base=/wd/hub --whitelisted-ips &

      # Verify Chromedriver is running on port 4444
      - name: Verify Chromedriver on Port 4444
        run: |
          netstat -tuln | grep 4444 || { echo "Chromedriver not running on port 4444"; exit 1; }

      # Run integration tests using the web-server device
      - name: Run Integration Tests with Web-Server
        env:
          CHROME_EXECUTABLE: /usr/local/chromium/chrome --headless --disable-gpu --no-sandbox
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server