name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Explicitly set the Flutter version

      - name: Enable Web Support
        run: |
          flutter config --enable-web || echo "Web support already enabled"
          flutter devices # List available devices

      - name: Install Dependencies
        run: flutter pub get

      - name: Clean Build Setup
        run: |
          flutter clean
          flutter pub get

      - name: Linting
        run: flutter analyze

      - name: Unit Tests
        run: flutter test --coverage --test-randomize-ordering-seed=random

      - name: Widget Tests
        run: flutter test --coverage --test-randomize-ordering-seed=random

      - name: Build APK
        run: |
          sed -i 's/com.example.esteira_imc/com.YOURDOMAIN.esteira_imc/g' android/app/build.gradle
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk