name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GTK 3
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev # Install GTK 3

      - name: Install Build Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config # Install common build dependencies

      - name: Install Common Dependencies
        run: sudo apt-get update && sudo apt-get install -y mesa-utils libglu1-mesa # Install common dependencies

      - name: Install cpu-checker
        run: sudo apt-get update && sudo apt-get install -y cpu-checker

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Print Environment Variables
        run: env # Print environment variables

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0' # Use a compatible Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Linting
        run: flutter analyze

      - name: Run Tests
        run: flutter test