name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Updated to v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
      - name: Linting
        run: |
          flutter pub get
          flutter analyze
      - name: Unit Tests
        run: |
          flutter pub get
          flutter test --coverage --test-randomize-ordering-seed=random
      - name: Widget Tests
        run: |
          flutter pub get
          flutter test --coverage --test-randomize-ordering-seed=random
      - name: Build APK
        run: |
          sed -i 's/com.example.esteira_imc/com.YOURDOMAIN.esteira_imc/g' android/app/build.gradle
          sed -i 's/versionCode 1/versionCode 10/g' android/app/build.gradle
          sed -i 's/versionName "1.0.0"/versionName "1.0.1"/g' android/app/build.gradle
          flutter pub get
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: Integration Tests
        run: |
          flutter pub get
          flutter drive --device-id=emulator-5554 --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart