name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Dependencies for Headless Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libxss1 libasound2 fonts-liberation libappindicator3-1 libgbm-dev
      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get install -y chromium-browser chromium-chromedriver
          export PATH=$PATH:/usr/lib/chromium-browser/
      - name: Run Integration Tests
        env:
          CHROME_EXECUTABLE: google-chrome --headless --disable-gpu --no-sandbox
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d chrome