name: FlutterCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Unit Tests
        run: flutter test test/bmi_calculator_test.dart

      - name: Run Widget Tests
        run: flutter test test/widget_test.dart