name: FlutterCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgtk-3-dev \
            libx11-dev \
            libxcomposite-dev \
            libxdamage-dev \
            libxrandr-dev \
            libgbm-dev \
            libasound2-dev \
            mesa-utils \
            xvfb

      - name: Set up Virtual Display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build Linux App
        run: flutter build linux --verbose

      - name: Run Integration Tests
        run: flutter test integration_test/app_test.dart -d linux --verbose --timeout 20m