name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Enable web support for Flutter
      - name: Enable Flutter Web Support
        run: flutter config --enable-web

      # Install Firefox and Geckodriver
      - name: Install Firefox and Geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/bin/
          rm geckodriver-v0.33.0-linux64.tar.gz

          # Verify installations
          firefox --version
          geckodriver --version

      # Run integration tests using the web-server device
      - name: Run Integration Tests with Web-Server
        env:
          CHROME_EXECUTABLE: /usr/bin/firefox --headless
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d firefox