name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Enable web support for Flutter
      - name: Enable Flutter Web Support
        run: flutter config --enable-web

      # Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          npm install -g @puppeteer/browsers
          npx @puppeteer/browsers install chromedriver@stable

      # Verify ChromeDriver
      - name: Verify ChromeDriver Installation
        run: chromedriver --version

      # Start ChromeDriver
      - name: Start ChromeDriver
        run: |
          chromedriver --port=4444 &
          sleep 5 # Allow time for ChromeDriver to start

      # Verify Chrome Device
      - name: Verify Chrome Device
        run: flutter devices

      # Clear Flutter Cache
      - name: Clear Flutter Cache
        run: flutter clean && flutter pub get

      # Run Integration Tests with Web-Server
      - name: Run Integration Tests with Web-Server
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server