name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Enable web support for Flutter
      - name: Enable Flutter Web Support
        run: flutter config --enable-web

      # Install Chrome for Testing and Chromedriver
      - name: Install Chrome for Testing and Chromedriver
        run: |
          # Define Chrome version and URLs
          CHROME_VERSION="135.0.7049.114"
          CHROME_URL="https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chrome-linux64.zip"
          CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip"

          # Download and install Chrome for Testing
          wget $CHROME_URL -O chrome-linux64.zip
          unzip chrome-linux64.zip -d chrome-linux64
          sudo mv chrome-linux64 /usr/local/chrome

          # Download and install Chromedriver
          wget $CHROMEDRIVER_URL -O chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d chromedriver-linux64
          sudo mv chromedriver-linux64/chromedriver-linux64/chromedriver /usr/bin/

          # Verify installations
          /usr/local/chrome/chrome-linux64/chrome --version
          chromedriver --version

      # Verify Chrome Device
      - name: Verify Chrome Device
        run: flutter devices

      # Clear Flutter Cache
      - name: Clear Flutter Cache
        run: flutter clean && flutter pub get

      # Run Integration Tests with Web-Server
      - name: Run Integration Tests with Web-Server
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --device-timeout 60