name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Flutter Dependencies
        run: flutter pub get
      - name: Flutter Analyze
        run: flutter analyze
      - name: Run Unit and Widget Tests
        run: flutter test --coverage --test-randomize-ordering-seed=random

  web-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Enable Flutter Web
        run: flutter config --enable-web
      - name: Setup ChromeDriver
        run: |
          npm install -g @puppeteer/browsers
          npx @puppeteer/browsers install chromedriver@stable
      - name: Start ChromeDriver
        run: |
          chromedriver --port=4444 &
          sleep 5
      - name: Flutter Cache
        run: flutter clean && flutter pub get
      - name: Run Web Integration Tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server