name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: sudo apt-get update # Update the package list
      - run: sudo apt-get install -y libgtk-3-dev # Install gtk+-3.0
      - run: flutter pub get
      - run: flutter test # Run widget and unit tests
      - run: flutter test integration_test/app_test.dart -d linux # Run integration tests on Linux desktop