name: FlutterCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Build and Runtime Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libgtk-3-dev \
            libx11-dev \
            libxcomposite-dev \
            libxdamage-dev \
            libxrandr-dev \
            libgbm-dev \
            libasound2-dev \
            mesa-utils \
            xvfb

      - name: Set up virtual display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Linting
        run: flutter analyze

      - name: Unit Tests
        run: flutter test --coverage --test-randomize-ordering-seed=random

      - name: Clean Build
        run: flutter clean

      - name: Build Linux
        run: flutter build linux --verbose

      - name: Integration Tests (Desktop)
        run: flutter test integration_test/app_test.dart -d linux --verbose --timeout 30m