name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GTK 3
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev # Install GTK 3

      - name: Install Build Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config # Install common build dependencies

      - name: Install Common Dependencies
        run: sudo apt-get update && sudo apt-get install -y mesa-utils libglu1-mesa # Install common dependencies

      - name: Install cpu-checker
        run: sudo apt-get update && sudo apt-get install -y cpu-checker

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Print Environment Variables
        run: env # Print environment variables

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0' # Try a different Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Linting
        run: flutter analyze

      - name: Unit Tests
        run: flutter test --coverage --test-randomize-ordering-seed=random

      - name: Widget Tests
        run: flutter test --coverage --test-randomize-ordering-seed=random

      - name: Build APK
        run: |
          sed -i 's/com.example.esteira_imc/com.YOURDOMAIN.esteira_imc/g' android/app/build.gradle
          sed -i 's/versionCode 1/versionCode 10/g' android/app/build.gradle
          sed -i 's/versionName "1.0.0"/versionName "1.0.1"/g' android/app/build.gradle
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Clean Build
        run: flutter clean # Clean the build

      - name: Build Linux
        run: flutter build linux --verbose # Build with verbose output

      - name: Integration Tests (Desktop)
        run: flutter test integration_test/app_test.dart -d linux